name: Rust Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        target: 
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu	
          - aarch64-unknown-linux-gnu
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release
