name: Rust Build Release
on:
  push:
    branches: [ master ]

jobs:
  devrelease:
    runs-on: ubuntu-latest
    outputs:
      upload: ${{steps.get_upload_url.outputs.url}}
    steps:
      - name: Move Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: dev 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get upload url for release tagged dev
        id: get_upload_url
        run: |
          url=$(echo "$response" | jq -r '.[] | select(.tag_name == "dev") | .upload_url')
          echo "::set-output name=url::$url"
        env: 
          response: ${{ steps.get_latest_release.outputs.data }}
  build:
    needs: [devrelease]
    strategy:
      fail-fast: false
      matrix:
        target: 
          - x86_64-unknown-linux-gnu	
          - aarch64-unknown-linux-gnu
        os:
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release
      - name: Archive
        run: zip wemo-exporter-${{ matrix.target }}.zip -j ./target/${{ matrix.target }}/release/wemo-exporter
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.devrelease.outputs.upload}}
          asset_path: ./wemo-exporter-${{ matrix.target }}.zip
          asset_name: wemo-exporter-${{ matrix.target }}.zip
          asset_content_type: application/zip