name: Rust Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.targets.os }}
    strategy:
      matrix:
        targets: 
          - os: ubuntu-latest
            target: "x86_64-unknown-linux-gnu"
          - os: macOS-latest
            target: "x86_64-unknown-linux-gnu"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.targets.target }}
      - run: cargo build --release
